services:
  - type: web
    name: dec-masters-site
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
