services:
  - type: web
    name: dec-masters-site
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
